### ISSUE TITLE
Problemas con las aproximantes

### ISSUE THREAD

**Issue by soliviantar** [fsanzl/fonemas#1]
Hola, muchas gracias por compartir esto!

He estado intentando utilizar la librería y creo que más o menos lo he conseguido, pero he detectado algunos problemas en los resultados. No sé si es que no lo estoy utilizando bien.

He visto que hay algunas situaciones en las que no se utilizan las aproximantes cuando deberían y al revés. Si no me equivoco, los casos son:

- Uso de oclusivas (b, d, g) siempre al inicio de palabra (si no hay apóstrofo antes):
`a la biβljoˈteka / tu diˈneɾo / una gɾan kantiˈðað` (debería ser: `a la βiβljoˈteka / tu ðiˈneɾo / una ɣɾan kantiˈðað`)
pero lo hace correctamente si hay apóstrofo antes

- Uso de aproximantes (β, ð, ɣ) siempre al inicio de frase (después de pausa siempre deberían ser oclusivas) o después de apóstrofo, aunque vayan precedidas de m/n (deberían ser "b", "g" y "d") o de l (solo con "d"):
Inicio de frase: `βoj a la / ðe reˈpente / ɣaˈne ʝo` (debería ser:  `boj a la / de reˈpente / gaˈne ʝo`
Tras m/n/(l): `me esˈtoj akostumˈβɾando / aˈpɾendo aleˈman ˈðezðe /  ninˈɣuno` (debería ser: `me esˈtoj akostumˈbɾando / aˈpɾendo aleˈman ˈdezðe /  ninˈguno`

**Comment by fsanzl** [comment]
Muchas gracias por reportarlo. Con lo que has descrito, parece claro que el programa evalua la marca de acento primario como un grafema en lugar de como diacrítico, por lo que al considerar el clúster consonántico después de silabear, no ve ```<mb>``` sino ```<m'b>``` y, por por ello, tampoco ```<m>``` y ```<b>``` como contiguas. Creo que puedo arreglarlo rápidamente; en cuanto tenga un rato lo saco.

**Comment by soliviantar** [comment]
Gracias por la rápida respuesta!

Exacto, ese es el problema con el acento. 

Pero además está el problema con el inicio de frase, la primera palabra de una frase (o después de pausa, por ejemplo si hay una coma o un punto) deberían resultar en una oclusiva, pero salen aproximantes. 

Y al contrario, cuando van inmediatamente después de un espacio salen oclusivas, pero deberían ser aproximantes (a menos que haya `m`, `n` antes de `b`, `g`, `d`, o `l` antes de `d`, en cuyo caso se mantendrían oclusivas).
