### ISSUE TITLE
Sugerencia: opción para marcar la vocal tónica con tilde

### ISSUE THREAD

**Issue by soliviantar** [fsanzl/fonemas#2]
Si fuera posible, quizás estaría bien tener una opción para que el acento primario aparezca sobre la vocal con una tilde normal, en lugar de con apóstrofo. Por ejemplo, en lugar de `piˈmjenta`, usar `pimjénta`

Para mi caso sería lo más cómodo. No sé apenas nada de programación, así que no sé si añadir esta opción sería muy complicado o si la idea es ajustarse exclusivamente al estilo IPA.

**Comment by fsanzl** [comment]
En realidad, simplificaría el análisis desde el punto de vista técnico si se hace desde abajo, pues ahorraría evaluar cada carácter para determinar si es un sonido o una marca diacrítica. No lo descarto en el futuro, cuando tenga algo de tiempo.
