### ISSUE TITLE
Los espacios rompen las reglas fonotácticas

### ISSUE THREAD

**Issue by soliviantar** [fsanzl/fonemas#3]
Otra cosa que he notado, relacionada con la de las aproximantes. En general, parece que cuando hay un espacio, no se aplican los cambios por influencia de sonidos precedentes o posteriores.

Por ejemplo, `s` pasa a `z` correctamente antes de consonantes sonoras, por ejemplo en palabras como `desde` o `rasgo`, pero si hay un espacio no ocurre (por ejemplo `es de` o `las gallinas` o `es nuevo`). 

Pasa lo mismo con `n > m` ante `b` o `p` (funciona en  `invitar`, pero no en `un bar` o `un poco`). 

También sucede con `n > ŋ` antes `g` o `k`. Funciona en `nunca`, pero no en `un gato`.

**Comment by fsanzl** [comment]
Solucionado en #4.
